name: Sync Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
    paths:
      - scripts/gcoresposter/cli.py
      - scripts/gen.py

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sync script
        run: |
          python scripts/gen.py

      - name: Make svg GitHub profile
        run: |
          python scripts/gcoresposter/cli.py --special-likes 500 --special-likes2 1000 --special-color '#0f99a1' --special-color2 '#f44336'

      - name: Push new audio
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m 'update new audio' || echo "nothing to commit"
          git push || echo "nothing to push"
